/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch.vue')['default']
    ShoppingListCard: typeof import('./src/components/ShoppingListCard.vue')['default']
    ShoppingListDialog: typeof import('./src/components/ShoppingListDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    ThemeOptions: typeof import('./src/components/ThemeOptions.vue')['default']
  }
}
